### ISSUE TITLE
Change the package.json name

### ISSUE THREAD

**Issue by kitsonk** [dojo/dijit-themes#18]
We should likely change the `package.json` name to something that won't collide on npm, like `dojo-themes`.

**Comment by dylans** [comment]
Makes sense, I'll address this weekend.

We do have @dojo for scoped npm packages which we could use, e.g. @dojo/themes rather than dojo-themes, but I've not had time to research the implications of scoped packages ( https://docs.npmjs.com/getting-started/scoped-packages )

**Comment by dylans** [comment]
Closed via b878942.
