### ISSUE TITLE
Screenshots of the new flat theme

### ISSUE THREAD

**Issue by silverqx** [dojo/dijit-themes#2]
Hi, 

It's possible to add some preview screenshots to the Readme.md for the new flat theme? 

I'm really impatient about this new flat theme :smile: 

Thank you.

**Comment by Jimflip** [comment]
+1

**Comment by btfou** [comment]
<img width="1021" alt="screen shot 2015-08-29 at 3 41 53 pm" src="https://cloud.githubusercontent.com/assets/4641297/9564775/6cae1f44-4e65-11e5-8415-5c8b5b68875a.png">

Or better yet try it out and provide feedback. https://github.com/dojo/themes/pull/4 has first major updates since initial.

**Comment by KateHodge** [comment]
This looks really good.  Even better than a screen shot would be a live demo.  I used the dbootstrap live demo all the time during development of an application as it's useful to be able to look at / interact with all the components and pick which one you want.  As that's no longer being maintained, I'll definitely want to try this one for the next project.

**Comment by dylans** [comment]
@sbhodge80 you can install it now, following the instructions at https://github.com/dojo/themes/blob/master/README.md . We are going to land a patch in the next day or two that moves the directory structure around, but it's pretty easy to grab a copy now.

Once we get it stable, we plan to add it to the dojo releases which will make a live demo even easier.

**Comment by wkeese** [comment]
FYI, you can see it running now just by pulling the code and then loading themes/ dijit/themes/flat/flat_test.html in a browser.  (That path will be themes/flat/tests/flat.html after #6).

**Comment by dylans** [comment]
Screenshot from above added to readme.
