### ISSUE TITLE
Update bower package registry

### ISSUE THREAD

**Issue by MChorfa** [dojo/dijit-themes#47]
Bower registry still pointing to the old repo instead of this one. 
I'll be happy to update the bower registry, but I am not the owner of this project, it seems the way to go to update registry package

**Comment by agubler** [comment]
Hi @MChorfa we’ve updated the url to point at the new location, have tried running `bower cache clean`?

**Comment by MChorfa** [comment]
Thank you for your feedback, actually, we were pointing to [https://bower.herokuapp.com](https://bower.herokuapp.com) instead of [https://registry.bower.io](https://registry.bower.io),  and [https://bower.herokuapp.com/packages/dojo-themes](https://bower.herokuapp.com/packages/dojo-themes) do trigger a timeout.

**Comment by dylans** [comment]
I'm not sure there's much we can do about someone else's copy of the bower registry? Presumably it will get synced at some point?

**Comment by MChorfa** [comment]
Yes, issue resolved. Thank you :)
